module.exports = {
  STATE_NORMAL: 'NORMAL',
  STATE_NO_PASSWD: 'NO_PASSWD',
  STATE_NO_ACCOUNT: 'ERR_NO_ACCOUNT',

  STATE_ERR_UNKNOWN: 'ERR_UNKNOWN',
  STATE_ERR_NO_CARD: 'ERR_NO_CARD',
  STATE_ERR_INTERNAL: 'ERR_INTERNAL'
}